"""CPG / NIST CSF regex catalog. Unknown names stay UNMAPPED — never fake a CVE."""

from __future__ import annotations

import re
from typing import Any

# Conservative observed-misconfig titles only. HTTP parsers never emit SMBv1.
CATALOG: list[dict[str, Any]] = [
    {
        "match": re.compile(r"cleartext http", re.I),
        "weakness": "Cleartext HTTP",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "Enforce TLS; redirect HTTP to HTTPS.",
        "severity": "medium",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"missing hsts", re.I),
        "weakness": "Missing HSTS",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "After TLS is enforced, add Strict-Transport-Security.",
        "severity": "medium",
        "csf_function": "protect",
    },
    {
        "match": re.compile(
            r"missing x-frame-options|missing csp|missing web security headers", re.I
        ),
        "weakness": "Missing web security headers",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.PS-01"],
        "action": "Set X-Frame-Options (or frame-ancestors) and Content-Security-Policy.",
        "severity": "low",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"server banner disclosure", re.I),
        "weakness": "Server banner disclosure",
        "cpg": ["CPG 2.T"],
        "csf": ["PR.PS-01"],
        "action": "Remove or genericize the Server header.",
        "severity": "low",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"insecure session cookie", re.I),
        "weakness": "Insecure session cookie",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.AA-05", "PR.DS-02"],
        "action": "Set Secure and HttpOnly on session cookies.",
        "severity": "medium",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"permissive cors", re.I),
        "weakness": "Permissive CORS policy",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.AA-05", "PR.DS-02"],
        "action": "Do not use Access-Control-Allow-Origin: *; list explicit origins.",
        "severity": "low",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"sslv3|ssl 3", re.I),
        "weakness": "SSLv3 enabled",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "Disable SSLv3; require TLS 1.2+.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"tls ?1\.0", re.I),
        "weakness": "TLS 1.0 enabled",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "Disable TLS 1.0; require TLS 1.2+.",
        "severity": "medium",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"tls ?1\.1", re.I),
        "weakness": "TLS 1.1 enabled",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "Disable TLS 1.1; require TLS 1.2+.",
        "severity": "medium",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"untrusted tls|self[- ]signed", re.I),
        "weakness": "Untrusted TLS certificate",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02", "PR.DS-10"],
        "action": "Replace self-signed or untrusted certificates with a public or private CA cert.",
        "severity": "medium",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"\btelnet\b", re.I),
        "weakness": "Telnet exposed",
        "cpg": ["CPG 2.H"],
        "csf": ["PR.PS-01"],
        "action": "Disable telnet; replace with SSH.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"\bftp\b", re.I),
        "weakness": "FTP exposed",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "Replace FTP with SFTP/FTPS; do not offer cleartext file transfer.",
        "severity": "medium",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"anonymous tls cipher|anonymous (dh|ecdh)", re.I),
        "weakness": "Anonymous TLS cipher",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "Disable anonymous DH/ECDH ciphers; require authenticated key exchange.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"smbv1|smb v1", re.I),
        "weakness": "SMBv1 enabled",
        "cpg": ["CPG 2.W"],
        "csf": ["PR.DS-02"],
        "action": "Disable SMBv1; restrict TCP/445 to the admin network.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"\bredis\b", re.I),
        "weakness": "Redis exposed",
        "cpg": ["CPG 2.T", "CPG 2.A"],
        "csf": ["PR.AA-05", "PR.DS-02"],
        "action": "Do not publish Redis; bind to localhost or a private net and require AUTH/TLS.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"postgresql|postgres", re.I),
        "weakness": "PostgreSQL exposed",
        "cpg": ["CPG 2.T", "CPG 2.A"],
        "csf": ["PR.AA-05", "PR.DS-02"],
        "action": "Do not publish PostgreSQL; bind to localhost or a private net and require TLS+auth.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"\bmemcached?\b", re.I),
        "weakness": "Memcached exposed",
        "cpg": ["CPG 2.T", "CPG 2.A"],
        "csf": ["PR.AA-05", "PR.DS-02"],
        "action": "Do not publish Memcached; bind to localhost or a private net and require SASL.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"phpmyadmin|php my admin", re.I),
        "weakness": "phpMyAdmin interface exposed",
        "cpg": ["CPG 2.T", "CPG 2.A"],
        "csf": ["PR.AA-05", "PR.PS-01"],
        "action": "Do not expose phpMyAdmin on a public listener; restrict to admin networks and require TLS+MFA.",
        "severity": "high",
        "csf_function": "protect",
    },
    {
        "match": re.compile(r"werkzeug|flask development|flask:", re.I),
        "weakness": "Werkzeug/Flask development server exposed",
        "cpg": ["CPG 2.T"],
        "csf": ["PR.PS-01"],
        "action": "Do not publish Werkzeug/Flask debug servers; put the app behind a production WSGI/TLS terminator.",
        "severity": "medium",
        "csf_function": "protect",
    },
]
